# The Issue That Could Lose the Next Election for Democrats
_NYMAG by Andrew Sullivan_


`October 20, 2017 10/20/2017 9:21 am`

I don’t believe it’s disputable at this point that the most potent issue behind the rise of the far right in America and Europe is mass immigration. It’s a core reason that Trump is now president; it’s why the AfD is now the third-biggest party in the German, yes, German, parliament; it’s why Austria’s new chancellor won by co-opting much of the far right’s agenda on immigration; it’s why Britain is attempting (and currently failing) to leave the EU; it’s why Marine Le Pen won a record number of votes for her party in France this spring. A critical moment, in retrospect, came with Angela Merkel’s 2015 decision to import over a million Syrian refugees into the heart of Europe. I’ve no doubt her heart was in the right place, but the political naïveté was stunning. How distant from the lives and views of most people does an elite have to be to see nothing to worry about from such drastic social and cultural change? Michael Brendan Dougherty elegantly explains here the dynamic that followed. There are now new borders and fences going up all over Europe, as a response to Merkel’s blithe misjudgment.

You would think that parties of the center-left would grapple with this existential threat to their political viability. And some have. One reason Britain’s Labour Party has done well in the last couple of years is that it has recognized the legitimacy of the issue. During the Brexit referendum, their leader, Jeremy Corbyn, expressed ambivalence toward remaining in the EU, careful not to lose his working-class base to the Europhobic right, recognizing the fears so many of his own supporters had about the impact of mass immigration on their lives, jobs, and culture. Even someone as leftist as Corbyn chose to be a pragmatist, trying to gain power, rather than a purist who might otherwise condemn his own voters as deplorable. And this is one reason why I have dwindling hopes that the Democratic Party will be able to defeat Trump in 2020. Instead of adjusting to this new reality, and listening to the electorate, the Dems have moved ever farther to the left, and are controlled by ever-radicalizing activists. There’s a nuanced, smart — and shockingly honest — piece in Vox by Dara Lind about this. Money quote:

    For Democrats, it’s been a simple calculus. Democrats’ attempts at “tough love” centrism didn’t win them any credit across the aisle, while an increasingly empowered immigrant-rights movement started calling them to task for the adverse consequences of enforcement policies. Democrats learned to ignore the critics on the right they couldn’t please, and embrace the critics on the left who they could.

Lind is right about the perverse politics of Obama’s centrism. He ramped up enforcement on the border and deportations … only to get nothing from the GOP in return. The right dismissed his toughness, while the left resented it. But it’s also true that Obama never truly bragged about his tough-on-illegal-immigrants stance, or campaigned on it, or emphasized it, when addressing the country as a whole. He couldn’t bring himself to boast about deportations, which is to his credit. But it’s hard to use tougher enforcement as leverage for a pathway to citizenship for those already here when you keep silent about it. The activist reaction — a rejection of most immigration enforcement or, with sanctuary cities, an open defiance of it — just makes this worse and renders a sane immigration compromise even more remote. Sure, the Latino activists are not the most to blame. The GOP base spent the last few years resisting any measure that could balance tougher border security and law enforcement with a path to citizenship. But when a glimmer of hope emerged recently with a potential Schumer-Pelosi-Trump deal on DACA, the Dreamer activists united with Stephen Miller to kill it. Lind spells out the state of play:

    Democrats in 2017, in general, tend to criticize the use of immigration enforcement, and tend to side with those accused of violating immigration law, as a broad matter of principle beyond opposing the particular actions of the administration … Democrats are no longer as willing to attack “illegal immigration” as a fundamental problem anymore.

This is, to be blunt, political suicide. The Democrats’ current position seems to be that the Dreamer parents who broke the law are near heroes, indistinguishable from the children they brought with them; and their rhetoric is very hard to distinguish, certainly for most swing voters, from a belief in open borders. In fact, the Democrats increasingly seem to suggest that any kind of distinction between citizens and noncitizens is somehow racist. You could see this at the last convention, when an entire evening was dedicated to Latinos, illegal and legal, as if the rule of law were largely irrelevant. Hence the euphemism “undocumented” rather than “illegal.” So the stage was built, lit, and set for Trump.

He still tragically owns that stage. What Merkel did for the AfD, the Democrats are in danger of doing for the Trump wing of the GOP. The most powerful thing Trump said in the campaign, I’d argue, was: “If you don’t have borders, you don’t have a country.” And the Democrats had no answer, something that millions of Americans immediately saw. They still formally favor enforcement of immigration laws, but rhetorically, they keep signaling the opposite. Here is Dylan Matthews, also in Vox, expressing the emerging liberal consensus: “Personally, I think any center-left party worth its salt has to be deeply committed to egalitarianism, not just for people born in the U.S. but for everyone … It means treating people born outside the U.S. as equals … And it means a strong presumption in favor of open immigration.” Here’s Zack Beauchamp, a liberal friend of mine: “What if I told you that immigration restrictionism is and always has been racist?” Borders themselves are racist? Seriously?

The entire concept of a nation whose citizens solely determine its future — the core foundation for any viable democracy at all — is now deemed by many left-liberals to be a function of bigotry. This is the kind of madness that could keep them from power indefinitely.

For me, as regular readers know, few things seem as ominous as the fate of free speech in the West. In democratic countries without a First Amendment, writers and speakers are now routinely hauled into court for hurting someone’s feelings or violating some new PC edict. In Canada, it is now a crime to use pronouns that have served the English language well enough for centuries, if you are not careful. You are compelled by law to say “ze” or “xe” or “ve” or an endlessly proliferating litany of gobbledygook — “(f)aer,” “e/ey,” “perself” — invented out of thin air by postmodern transgenderists. Justin Trudeau doesn’t just want you to be criminalized for saying things he regards as “hate,” he wants to use the criminal law to force you to say things you don’t believe in and can’t even remember.

In Britain, meanwhile, it is now a criminal offense to post something on social media that “is perceived by the victim or any other person, to be motivated by hostility or prejudice.” “Hostility” is defined thus: “ill-will, spite, contempt, prejudice, unfriendliness, antagonism, resentment and dislike.” In other words, if you “dislike” some idea, and someone else asserts your view is driven by “unfriendliness” to a member of a minority, you are breaking the law. There is effectively no free speech left in the U.K. that isn’t subject to a criminal veto by someone seeking to make trouble or permanently primed to take offense. And that is not to speak of the chilling effect such laws have on others too intimidated to open their mouths at all.

In America, thanks to Thomas Jefferson et al., such policing of minds and thoughts by the government is forbidden. So the illiberal left and reactionary right find other ways. Our president believes “it’s frankly disgusting the way the press is able to write whatever they want to write.” He also thinks he can coerce people into saying “Merry Christmas” or standing for the national anthem. (I’ve decided to reverse my previous custom and always say “Happy Holidays” and always kneel for the anthem.) The GOP candidate for the Senate from Alabama — supported by every other GOP senator — believes that NFL players are actually breaking the law by using their First Amendment rights, and that Muslims should be barred from public office. And then the worst news on this front all year: “Nearly half of voters, 46 percent, believe the news media fabricate news stories about President Donald Trump and his administration.” That rises to 76 percent of Republicans. Twenty-eight percent of all voters — and 46 percent of Republicans — believe that the government should be able to remove the licenses from outlets that criticize the president. The First Amendment lives; but the beliefs and practices and norms that buttress it are atrophying very fast.

Many now demand, for example, that young-adult fiction conform to their ideology … or they will destroy a book before it is even published and before they have even read it. That just happened to a book written by Laura Moriarty, called American Heart, which was subjected to a social-media version of book-burning. Kirkus originally gave the book a glowing review, and then retracted it under pressure, then got the reviewer to rewrite it. Vulture interviewed the editor of Kirkus Reviews about the flap. Money quote:

    “Obviously we don’t like having to make corrections after the publication of a review,” [Kirkus’s editor-in-chief Claiborne Smith] adds. “The plan is to beef up our editing of reviews in this section, to have further eyes before it goes to print.”

    In the future, I ask, is the goal that no problematic book will escape un-called-out?

    “That’s certainly the goal!” Smith says, with the caveat that Kirkus’s critics aren’t infallible. “I mean, we’re human beings.”

Or look at what happened to a speaker from the ACLU at the College of William & Mary in Virginia a couple of weeks back. She came to give a talk about — yes! — free speech, only to be shouted down by the usual mob, who were at least honest enough to chant: “Liberalism Is White Supremacy,” and “The Revolution Will Not Uphold Your Constitution.” They physically prevented the speaker from even talking one-on-one with those who were interested in a dialogue.

The unity of the far left and the Trump right on this is as striking as it is depressing. What they share is a contempt for liberal democracy. Truth to both of them is merely an instrument of power. Instead of relying on an open exchange of ideas in order to determine the always-provisional truth, both sides (yes, both sides) insist that they already know the truth and need simply to acquire the power to impose it on everyone else. Somewhere, Thomas Jefferson weeps.

I wasn’t prepared for Ken Burns’s and Lynn Novick’s documentary on the Vietnam War. I foolishly thought I knew about what happened. And I did, in some abstract way. Buried in my brain were ideas about campus violence, war crimes, and a “Vietnam Syndrome” that my generation of conservatives wanted to overcome. I knew that the Tet Offensive had actually failed in Vietnam but succeeded in destroying America’s will to fight on. I’d listened to late-night drunken rants by Hitchens about Henry Kissinger; I knew the casualties; I had visions from various Oliver Stone movies; I’d visited the Memorial many times; I’d read histories; I’d even written about the lingering divides in America that stem from that divisive conflict.

But it was all a series of disconnected scenes and ideas in my head and consciousness. I wasn’t born when Kennedy walked backward into a conflict utterly irrelevant to the security of the United States. I was barely in high school in another country when the war ended. And what the documentary series did for me was to force me to confront the reality of what happened, its enormity, its nihilism, and its architectonic role in precipitating the unraveling of this country. The video images and in-person interviews and the power of the fully elaborated narrative itself affect you more than anything else can. Seeing how a single family was torn apart over the years; watching the staggering videos of unwinnable battles; observing the fathomless agony of the Vietnamese people themselves; seeing their faces contorted with grief or resignation or hatred: This made it human to me for the first time. Sometimes video can distort, but the documentary manages to balance these unforgettable images with enough context to absorb them with understanding as well as horror.

I wonder if I had watched this documentary before the Iraq War, I might have been able to wrestle free of the confirmation bias and emotional fervor that led me into a decision I’m now deeply ashamed of. I’m ashamed not because I didn’t support the war in good faith; I’m ashamed because I did. And it took a willful blindness to push out of my consciousness what this documentary insists upon: the way patriotism can easily morph into nationalism and nationalism can segue all too easily into carnage. No, this does not make me a pacifist. But it does make me much, much leerier of war in all its forms, and of the hideous lessons of originally noble intentions. And if the combination of LBJ and Vietnam gave us such horror, it’s had to imagine what Trump could mindlessly provoke with North Korea, a power with nuclear weapons.

On that cheerful note, see you next Friday.
The Issue That Could Lose the Next Election for Democrats

